package online.fivem.common.gtav

object NativeControls {

	enum class Groups(val index: Int) {
		MOVE(0),
		LOOK(1),
		WHEEL(2),
		CELLPHONE_NAVIGATE(3),
		CELLPHONE_NAVIGATE_UD(4),
		CELLPHONE_NAVIGATE_LR(5),
		FRONTEND_DPAD_ALL(6),
		FRONTEND_DPAD_UD(7),
		FRONTEND_DPAD_LR(8),
		FRONTEND_LSTICK_ALL(9),
		FRONTEND_RSTICK_ALL(10),
		FRONTEND_GENERIC_UD(11),
		FRONTEND_GENERIC_LR(12),
		FRONTEND_GENERIC_ALL(13),
		FRONTEND_BUMPERS(14),
		FRONTEND_TRIGGERS(15),
		FRONTEND_STICKS(16),
		SCRIPT_DPAD_ALL(17),
		SCRIPT_DPAD_UD(18),
		SCRIPT_DPAD_LR(19),
		SCRIPT_LSTICK_ALL(20),
		SCRIPT_RSTICK_ALL(21),
		SCRIPT_BUMPERS(22),
		SCRIPT_TRIGGERS(23),
		WEAPON_WHEEL_CYCLE(24),
		FLY(25),
		SUB(26),
		VEH_MOVE_ALL(27),
		CURSOR(28),
		CURSOR_SCROLL(29),
		SNIPER_ZOOM_SECONDARY(30),
		VEH_HYDRAULICS_CONTROL(31);

	}

	enum class Keys(val index: Int) {

		NEXT_CAMERA(0), //	V
		LOOK_LR(1), //	MOUSE RIGHT
		LOOK_UD(2), //	MOUSE DOWN
		LOOK_UP_ONLY(3), //	(NONE)
		LOOK_DOWN_ONLY(4), //	MOUSE DOWN
		LOOK_LEFT_ONLY(5), //	(NONE)
		LOOK_RIGHT_ONLY(6), //	MOUSE RIGHT
		CINEMATIC_SLOWMO(7), //	(NONE)
		SCRIPTED_FLY_UD(8), //	S
		SCRIPTED_FLY_LR(9), //	D
		SCRIPTED_FLY_ZUP(10), //	PAGEUP
		SCRIPTED_FLY_ZDOWN(11), //	PAGEDOWN
		WEAPON_WHEEL_UD(12), //	MOUSE DOWN
		WEAPON_WHEEL_LR(13), //	MOUSE RIGHT
		WEAPON_WHEEL_NEXT(14), //	SCROLLWHEEL DOWN
		WEAPON_WHEEL_PREV(15), //	SCROLLWHEEL UP
		SELECT_NEXT_WEAPON(16), //	SCROLLWHEEL DOWN
		SELECT_PREV_WEAPON(17), //	SCROLLWHEEL UP
		SKIP_CUTSCENE(18), //	ENTER / LEFT MOUSE BUTTON / SPACEBAR
		CHARACTER_WHEEL(19), //	LEFT ALT
		MULTIPLAYER_INFO(20), //	Z
		SPRINT(21), //	LEFT SHIFT
		JUMP(22), //	SPACEBAR
		ENTER(23), //	F
		ATTACK(24), //	LEFT MOUSE BUTTON
		AIM(25), //	RIGHT MOUSE BUTTON
		LOOK_BEHIND(26), //	C
		PHONE(27), //	ARROW UP / SCROLLWHEEL BUTTON (PRESS)
		SPECIAL_ABILITY(28), //	(NONE)
		SPECIAL_ABILITY_SECONDARY(29), //	B
		MOVE_LR(30), //	D
		MOVE_UD(31), //	S
		MOVE_UP_ONLY(32), //	W
		MOVE_DOWN_ONLY(33), //	S
		MOVE_LEFT_ONLY(34), //	A
		MOVE_RIGHT_ONLY(35), //	D
		DUCK(36), //	LEFT CTRL
		SELECT_WEAPON(37), //	TAB
		PICKUP(38), //	E
		SNIPER_ZOOM(39), //	[
		SNIPER_ZOOM_IN_ONLY(40), //	]
		SNIPER_ZOOM_OUT_ONLY(41), //	[
		SNIPER_ZOOM_IN_SECONDARY(42), //	]
		SNIPER_ZOOM_OUT_SECONDARY(43), //	[
		COVER(44), //	Q
		RELOAD(45), //	R
		TALK(46), //	E
		DETONATE(47), //	G
		HUD_SPECIAL(48), //	Z
		ARREST(49), //	F
		ACCURATE_AIM(50), //	SCROLLWHEEL DOWN
		CONTEXT(51), //	E
		CONTEXT_SECONDARY(52), //	Q
		WEAPON_SPECIAL(53), //	(NONE)
		WEAPON_SPECIAL_TWO(54), //	E
		DIVE(55), //	SPACEBAR
		DROP_WEAPON(56), //	F9
		DROP_AMMO(57), //	F10
		THROW_GRENADE(58), //	G
		VEH_MOVE_LR(59), //	D
		VEH_MOVE_UD(60), //	LEFT CTRL
		VEH_MOVE_UP_ONLY(61), //	LEFT SHIFT
		VEH_MOVE_DOWN_ONLY(62), //	LEFT CTRL
		VEH_MOVE_LEFT_ONLY(63), //	A
		VEH_MOVE_RIGHT_ONLY(64), //	D
		VEH_SPECIAL(65), //	(NONE)
		VEH_GUN_LR(66), //	MOUSE RIGHT
		VEH_GUN_UD(67), //	MOUSE DOWN
		VEH_AIM(68), //	RIGHT MOUSE BUTTON
		VEH_ATTACK(69), //	LEFT MOUSE BUTTON
		VEH_ATTACK2(70), //	RIGHT MOUSE BUTTON
		VEH_ACCELERATE(71), //	W
		VEH_BRAKE(72), //	S
		VEH_DUCK(73), //	X
		VEH_HEADLIGHT(74), //	H
		VEH_EXIT(75), //	F
		VEH_HANDBRAKE(76), //	SPACEBAR
		VEH_HOTWIRE_LEFT(77), //	W
		VEH_HOTWIRE_RIGHT(78), //	S
		VEH_LOOK_BEHIND(79), //	C
		VEH_CIN_CAM(80), //	R
		VEH_NEXT_RADIO(81), //	.
		VEH_PREV_RADIO(82), //	,
		VEH_NEXT_RADIO_TRACK(83), //	=
		VEH_PREV_RADIO_TRACK(84), //	-
		VEH_RADIO_WHEEL(85), //	Q
		VEH_HORN(86), //	E
		VEH_FLY_THROTTLE_UP(87), //	W
		VEH_FLY_THROTTLE_DOWN(88), //	S
		VEH_FLY_YAW_LEFT(89), //	A
		VEH_FLY_YAW_RIGHT(90), //	D
		VEH_PASSENGER_AIM(91), //	RIGHT MOUSE BUTTON
		VEH_PASSENGER_ATTACK(92), //	LEFT MOUSE BUTTON
		VEH_SPECIAL_ABILITY_FRANKLIN(93), //	(NONE)
		VEH_STUNT_UD(94), //	(NONE)
		VEH_CINEMATIC_UD(95), //	MOUSE DOWN
		VEH_CINEMATIC_UP_ONLY(96), //	NUMPAD- / SCROLLWHEEL UP
		VEH_CINEMATIC_DOWN_ONLY(97), //	NUMPAD+ / SCROLLWHEEL DOWN
		VEH_CINEMATIC_LR(98), //	MOUSE RIGHT
		VEH_SELECT_NEXT_WEAPON(99), //	SCROLLWHEEL UP
		VEH_SELECT_PREV_WEAPON(100), //	[
		VEH_ROOF(101), //	H
		VEH_JUMP(102), //	SPACEBAR
		VEH_GRAPPLING_HOOK(103), //	E
		VEH_SHUFFLE(104), //	H
		VEH_DROP_PROJECTILE(105), //	X
		VEH_MOUSE_CONTROL_OVERRIDE(106), //	LEFT MOUSE BUTTON
		VEH_FLY_ROLL_LR(107), //	NUMPAD 6
		VEH_FLY_ROLL_LEFT_ONLY(108), //	NUMPAD 4
		VEH_FLY_ROLL_RIGHT_ONLY(109), //	NUMPAD 6
		VEH_FLY_PITCH_UD(110), //	NUMPAD 5
		VEH_FLY_PITCH_UP_ONLY(111), //	NUMPAD 8
		VEH_FLY_PITCH_DOWN_ONLY(112), //	NUMPAD 5
		VEH_FLY_UNDERCARRIAGE(113), //	G
		VEH_FLY_ATTACK(114), //	RIGHT MOUSE BUTTON
		VEH_FLY_SELECT_NEXT_WEAPON(115), //	SCROLLWHEEL UP
		VEH_FLY_SELECT_PREV_WEAPON(116), //	[
		VEH_FLY_SELECT_TARGET_LEFT(117), //	NUMPAD 7
		VEH_FLY_SELECT_TARGET_RIGHT(118), //	NUMPAD 9
		VEH_FLY_VERTICAL_FLIGHT_MODE(119), //	E
		VEH_FLY_DUCK(120), //	X
		VEH_FLY_ATTACK_CAMERA(121), //	INSERT
		VEH_FLY_MOUSE_CONTROL_OVERRIDE(122), //	LEFT MOUSE BUTTON
		VEH_SUB_TURN_LR(123), //	NUMPAD 6
		VEH_SUB_TURN_LEFT_ONLY(124), //	NUMPAD 4
		VEH_SUB_TURN_RIGHT_ONLY(125), //	NUMPAD 6
		VEH_SUB_PITCH_UD(126), //	NUMPAD 5
		VEH_SUB_PITCH_UP_ONLY(127), //	NUMPAD 8
		VEH_SUB_PITCH_DOWN_ONLY(128), //	NUMPAD 5
		VEH_SUB_THROTTLE_UP(129), //	W
		VEH_SUB_THROTTLE_DOWN(130), //	S
		VEH_SUB_ASCEND(131), //	LEFT SHIFT
		VEH_SUB_DESCEND(132), //	LEFT CTRL
		VEH_SUB_TURN_HARD_LEFT(133), //	A
		VEH_SUB_TURN_HARD_RIGHT(134), //	D
		VEH_SUB_MOUSE_CONTROL_OVERRIDE(135), //	LEFT MOUSE BUTTON
		VEH_PUSHBIKE_PEDAL(136), //	W
		VEH_PUSHBIKE_SPRINT(137), //	CAPSLOCK
		VEH_PUSHBIKE_FRONT_BRAKE(138), //	Q
		VEH_PUSHBIKE_REAR_BRAKE(139), //	S
		MELEE_ATTACK_LIGHT(140), //	R
		MELEE_ATTACK_HEAVY(141), //	Q
		MELEE_ATTACK_ALTERNATE(142), //	LEFT MOUSE BUTTON
		MELEE_BLOCK(143), //	SPACEBAR
		PARACHUTE_DEPLOY(144), //	F / LEFT MOUSE BUTTON
		PARACHUTE_DETACH(145), //	F
		PARACHUTE_TURN_LR(146), //	D
		PARACHUTE_TURN_LEFT_ONLY(147), //	A
		PARACHUTE_TURN_RIGHT_ONLY(148), //	D
		PARACHUTE_PITCH_UD(149), //	S
		PARACHUTE_PITCH_UP_ONLY(150), //	W
		PARACHUTE_PITCH_DOWN_ONLY(151), //	S
		PARACHUTE_BRAKE_LEFT(152), //	Q
		PARACHUTE_BRAKE_RIGHT(153), //	E
		PARACHUTE_SMOKE(154), //	X
		PARACHUTE_PRECISION_LANDING(155), //	LEFT SHIFT
		MAP(156), //	(NONE)
		SELECT_WEAPON_UNARMED(157), //	1
		SELECT_WEAPON_MELEE(158), //	2
		SELECT_WEAPON_HANDGUN(159), //	6
		SELECT_WEAPON_SHOTGUN(160), //	3
		SELECT_WEAPON_SMG(161), //	7
		SELECT_WEAPON_AUTO_RIFLE(162), //	8
		SELECT_WEAPON_SNIPER(163), //	9
		SELECT_WEAPON_HEAVY(164), //	4
		SELECT_WEAPON_SPECIAL(165), //	5
		SELECT_CHARACTER_MICHAEL(166), //	F5
		SELECT_CHARACTER_FRANKLIN(167), //	F6
		SELECT_CHARACTER_TREVOR(168), //	F7
		SELECT_CHARACTER_MULTIPLAYER(169), //	F8 (CONSOLE)
		SAVE_REPLAY_CLIP(170), //	F3
		SPECIAL_ABILITY_PC(171), //	CAPSLOCK

		CELLPHONE_UP(172), //	ARROW UP
		CELLPHONE_DOWN(173), //	ARROW DOWN
		CELLPHONE_LEFT(174), //	ARROW LEFT
		CELLPHONE_RIGHT(175), //	ARROW RIGHT
		CELLPHONE_SELECT(176), //	ENTER / LEFT MOUSE BUTTON
		CELLPHONE_CANCEL(177), //	BACKSPACE / ESC / RIGHT MOUSE BUTTON
		CELLPHONE_OPTION(178), //	DELETE
		CELLPHONE_EXTRA_OPTION(179), //	SPACEBAR
		CELLPHONE_SCROLL_FORWARD(180), //	SCROLLWHEEL DOWN
		CELLPHONE_SCROLL_BACKWARD(181), //	SCROLLWHEEL UP
		CELLPHONE_CAMERA_FOCUS_LOCK(182), //	L
		CELLPHONE_CAMERA_GRID(183), //	G
		CELLPHONE_CAMERA_SELFIE(184), //	E
		CELLPHONE_CAMERA_DOF(185), //	F
		CELLPHONE_CAMERA_EXPRESSION(186), //	X

		FRONTEND_DOWN(187), //	ARROW DOWN
		FRONTEND_UP(188), //	ARROW UP
		FRONTEND_LEFT(189), //	ARROW LEFT
		FRONTEND_RIGHT(190), //	ARROW RIGHT
		FRONTEND_RDOWN(191), //	ENTER
		FRONTEND_RUP(192), //	TAB
		FRONTEND_RLEFT(193), //	(NONE)
		FRONTEND_RRIGHT(194), //	BACKSPACE
		FRONTEND_AXIS_X(195), //	D
		FRONTEND_AXIS_Y(196), //	S
		FRONTEND_RIGHT_AXIS_X(197), //	]
		FRONTEND_RIGHT_AXIS_Y(198), //	SCROLLWHEEL DOWN
		FRONTEND_PAUSE(199), //	P
		FRONTEND_PAUSE_ALTERNATE(200), //	ESC
		FRONTEND_ACCEPT(201), //	ENTER / NUMPAD ENTER
		FRONTEND_CANCEL(202), //	BACKSPACE / ESC
		FRONTEND_X(203), //	SPACEBAR
		FRONTEND_Y(204), //	TAB
		FRONTEND_LB(205), //	Q
		FRONTEND_RB(206), //	E
		FRONTEND_LT(207), //	PAGE DOWN
		FRONTEND_RT(208), //	PAGE UP
		FRONTEND_LS(209), //	LEFT SHIFT
		FRONTEND_RS(210), //	LEFT CONTROL
		FRONTEND_LEADERBOARD(211), //	TAB
		FRONTEND_SOCIAL_CLUB(212), //	HOME
		FRONTEND_SOCIAL_CLUB_SECONDARY(213), //	HOME
		FRONTEND_DELETE(214), //	DELETE
		FRONTEND_ENDSCREEN_ACCEPT(215), //	ENTER
		FRONTEND_ENDSCREEN_EXPAND(216), //	SPACEBAR
		FRONTEND_SELECT(217), //	CAPSLOCK
		SCRIPT_LEFT_AXIS_X(218), //	D
		SCRIPT_LEFT_AXIS_Y(219), //	S
		SCRIPT_RIGHT_AXIS_X(220), //	MOUSE RIGHT
		SCRIPT_RIGHT_AXIS_Y(221), //	MOUSE DOWN
		SCRIPT_RUP(222), //	RIGHT MOUSE BUTTON
		SCRIPT_RDOWN(223), //	LEFT MOUSE BUTTON
		SCRIPT_RLEFT(224), //	LEFT CTRL
		SCRIPT_RRIGHT(225), //	RIGHT MOUSE BUTTON
		SCRIPT_LB(226), //	(NONE)
		SCRIPT_RB(227), //	(NONE)
		SCRIPT_LT(228), //	(NONE)
		SCRIPT_RT(229), //	LEFT MOUSE BUTTON
		SCRIPT_LS(230), //	(NONE)
		SCRIPT_RS(231), //	(NONE)
		SCRIPT_PAD_UP(232), //	W
		SCRIPT_PAD_DOWN(233), //	S
		SCRIPT_PAD_LEFT(234), //	A
		SCRIPT_PAD_RIGHT(235), //	D
		SCRIPT_SELECT(236), //	V
		CURSOR_ACCEPT(237), //	LEFT MOUSE BUTTON
		CURSOR_CANCEL(238), //	RIGHT MOUSE BUTTON
		CURSOR_X(239), //	(not a key, counts as being pressed if the mouse is on the right side of the screen)
		CURSOR_Y(240), //	(not a key, counts as being pressed if the mouse is on the left side of the screen)
		CURSOR_SCROLL_UP(241), //	SCROLLWHEEL UP
		CURSOR_SCROLL_DOWN(242), //	SCROLLWHEEL DOWN
		ENTER_CHEAT_CODE(243), //	~ / `
		INTERACTION_MENU(244), //	M
		MP_TEXT_CHAT_ALL(245), //	T
		MP_TEXT_CHAT_TEAM(246), //	Y
		MP_TEXT_CHAT_FRIENDS(247), //	(NONE)
		MP_TEXT_CHAT_CREW(248), //	(NONE)
		PUSH_TO_TALK(249), //	N
		CREATOR_LS(250), //	R
		CREATOR_RS(251), //	F
		CREATOR_LT(252), //	X
		CREATOR_RT(253), //	C
		CREATOR_MENU_TOGGLE(254), //	LEFT SHIFT
		CREATOR_ACCEPT(255), //	SPACEBAR
		CREATOR_DELETE(256), //	DELETE
		ATTACK2(257), //	LEFT MOUSE BUTTON
		RAPPEL_JUMP(258), //	(NONE)
		RAPPEL_LONG_JUMP(259), //	(NONE)
		RAPPEL_SMASH_WINDOW(260), //	(NONE)
		PREV_WEAPON(261), //	SCROLLWHEEL UP
		NEXT_WEAPON(262), //	SCROLLWHEEL DOWN
		MELEE_ATTACK1(263), //	R
		MELEE_ATTACK2(264), //	Q
		WHISTLE(265), //	(NONE)
		MOVE_LEFT(266), //	D
		MOVE_RIGHT(267), //	D
		MOVE_UP(268), //	S
		MOVE_DOWN(269), //	S
		LOOK_LEFT(270), //	MOUSE RIGHT
		LOOK_RIGHT(271), //	MOUSE RIGHT
		LOOK_UP(272), //	MOUSE DOWN
		LOOK_DOWN(273), //	MOUSE DOWN
		SNIPER_ZOOM_IN(274), //	[
		SNIPER_ZOOM_OUT(275), //	[
		SNIPER_ZOOM_IN_ALTERNATE(276), //	[
		SNIPER_ZOOM_OUT_ALTERNATE(277), //	[
		VEH_MOVE_LEFT(278), //	D
		VEH_MOVE_RIGHT(279), //	D
		VEH_MOVE_UP(280), //	LEFT CTRL
		VEH_MOVE_DOWN(281), //	LEFT CTRL
		VEH_GUN_LEFT(282), //	MOUSE RIGHT
		VEH_GUN_RIGHT(283), //	MOUSE RIGHT
		VEH_GUN_UP(284), //	MOUSE RIGHT
		VEH_GUN_DOWN(285), //	MOUSE RIGHT
		VEH_LOOK_LEFT(286), //	MOUSE RIGHT
		VEH_LOOK_RIGHT(287), //	MOUSE RIGHT
		REPLAY_START_STOP_RECORDING(288), //	F1
		REPLAY_START_STOP_RECORDING_SECONDARY(289), //	F2
		SCALED_LOOK_LR(290), //	MOUSE RIGHT
		SCALED_LOOK_UD(291), //	MOUSE DOWN
		SCALED_LOOK_UP_ONLY(292), //	(NONE)
		SCALED_LOOK_DOWN_ONLY(293), //	(NONE)
		SCALED_LOOK_LEFT_ONLY(294), //	(NONE)
		SCALED_LOOK_RIGHT_ONLY(295), //	(NONE)
		REPLAY_MARKER_DELETE(296), //	DELETE
		REPLAY_CLIP_DELETE(297), //	DELETE
		REPLAY_PAUSE(298), //	SPACEBAR
		REPLAY_REWIND(299), //	ARROW DOWN
		REPLAY_FFWD(300), //	ARROW UP
		REPLAY_NEWMARKER(301), //	M
		REPLAY_RECORD(302), //	S
		REPLAY_SCREENSHOT(303), //	U
		REPLAY_HIDEHUD(304), //	H
		REPLAY_STARTPOINT(305), //	B
		REPLAY_ENDPOINT(306), //	N
		REPLAY_ADVANCE(307), //	ARROW RIGHT
		REPLAY_BACK(308), //	ARROW LEFT
		REPLAY_TOOLS(309), //	T
		REPLAY_RESTART(310), //	R
		REPLAY_SHOWHOTKEY(311), //	K
		REPLAY_CYCLEMARKERLEFT(312), //	[
		REPLAY_CYCLEMARKERRIGHT(313), //	]
		REPLAY_FOVINCREASE(314), //	NUMPAD +
		REPLAY_FOVDECREASE(315), //	NUMPAD -
		REPLAY_CAMERAUP(316), //	PAGE UP
		REPLAY_CAMERADOWN(317), //	PAGE DOWN
		REPLAY_SAVE(318), //	F5
		REPLAY_TOGGLETIME(319), //	C
		REPLAY_TOGGLETIPS(320), //	V
		REPLAY_PREVIEW(321), //	SPACEBAR
		REPLAY_TOGGLE_TIMELINE(322), //	ESC
		REPLAY_TIMELINE_PICKUP_CLIP(323), //	X
		REPLAY_TIMELINE_DUPLICATE_CLIP(324), //	C
		REPLAY_TIMELINE_PLACE_CLIP(325), //	V
		REPLAY_CTRL(326), //	LEFT CTRL
		REPLAY_TIMELINE_SAVE(327), //	F5
		REPLAY_PREVIEW_AUDIO(328), //	SPACEBAR
		VEH_DRIVE_LOOK(329), //	LEFT MOUSE BUTTON
		VEH_DRIVE_LOOK2(330), //	RIGHT MOUSE BUTTON
		VEH_FLY_ATTACK2(331), //	RIGHT MOUSE BUTTON
		RADIO_WHEEL_UD(332), //	MOUSE DOWN
		RADIO_WHEEL_LR(333), //	MOUSE RIGHT
		VEH_SLOWMO_UD(334), //	SCROLLWHEEL DOWN
		VEH_SLOWMO_UP_ONLY(335), //	SCROLLWHEEL UP
		VEH_SLOWMO_DOWN_ONLY(336), //	SCROLLWHEEL DOWN
		VEH_HYDRAULICS_CONTROL_TOGGLE(337), //	X
		VEH_HYDRAULICS_CONTROL_LEFT(338), //	A
		VEH_HYDRAULICS_CONTROL_RIGHT(339), //	D
		VEH_HYDRAULICS_CONTROL_UP(340), //	LEFT SHIFT
		VEH_HYDRAULICS_CONTROL_DOWN(341), //	LEFT CTRL
		VEH_HYDRAULICS_CONTROL_UD(342), //	D
		VEH_HYDRAULICS_CONTROL_LR(343), //	LEFT CTRL
		MAP_POI(344), //	F11
		REPLAY_SNAPMATIC_PHOTO(345); //	X

	}
}