package online.fivem.common.gtav

enum class RadioStation(val code: String) {
	RADIO_01_CLASS_ROCK("RADIO_01_CLASS_ROCK"),  // Los Santos Rock Radio
	RADIO_02_POP("RADIO_02_POP"),         // Non-Stop-Pop FM
	RADIO_03_HIPHOP_NEW("RADIO_03_HIPHOP_NEW"),  // Radio Los Santos
	RADIO_04_PUNK("RADIO_04_PUNK"),        // Channel X
	RADIO_05_TALK_01("RADIO_05_TALK_01"),     // West Coast Talk Radio
	RADIO_06_COUNTRY("RADIO_06_COUNTRY"),     // Rebel Radio
	RADIO_07_DANCE_01("RADIO_07_DANCE_01"),    // Soulwax FM
	RADIO_08_MEXICAN("RADIO_08_MEXICAN"),     // East Los FM
	RADIO_09_HIPHOP_OLD("RADIO_09_HIPHOP_OLD"),  // West Coast Classics

	RADIO_11_TALK_02("RADIO_11_TALK_02"),      // Blaine County Radio;
	RADIO_12_REGGAE("RADIO_12_REGGAE"),      // Blue Ark
	RADIO_13_JAZZ("RADIO_13_JAZZ"),        // Worldwide FM
	RADIO_14_DANCE_02("RADIO_14_DANCE_02"),    // FlyLo FM
	RADIO_15_MOTOWN("RADIO_15_MOTOWN"),      // The Lowdown 91.1
	RADIO_16_SILVERLAKE("RADIO_16_SILVERLAKE"),  // Radio Mirror Park
	RADIO_17_FUNK("RADIO_17_FUNK"),        // Space 103.2
	RADIO_18_90S_ROCK("RADIO_18_90S_ROCK"),    // Vinewood Boulevard Radio
	RADIO_19_USER("RADIO_19_USER"),        // Self Radio
	RADIO_20_THELAB("RADIO_20_THELAB"),      // The Lab

	RADIO_21_XM17("RADIO_21_DLC_XM17"), // Blonded Los Santos 97.8 FM
	RADIO_22_BATTLE_MIX1_RADIO("RADIO_22_DLC_BATTLE_MIX1_RADIO"),//LS UR

	//??
	RADIO_23_DLC_BATTLE_MIX2_CLUB("RADIO_23_DLC_BATTLE_MIX2_CLUB"),
	RADIO_24_DLC_BATTLE_MIX3_CLUB("RADIO_24_DLC_BATTLE_MIX3_CLUB"),
	RADIO_25_DLC_BATTLE_MIX4_CLUB("RADIO_25_DLC_BATTLE_MIX4_CLUB"),
	RADIO_26_DLC_BATTLE_CLUB_WARMUP("RADIO_26_DLC_BATTLE_CLUB_WARMUP"),

	DLC_BATTLE_MIX1_CLUB_PRIV("DLC_BATTLE_MIX1_CLUB_PRIV"),
	DLC_BATTLE_MIX2_CLUB_PRIV("DLC_BATTLE_MIX2_CLUB_PRIV"),
	DLC_BATTLE_MIX3_CLUB_PRIV("DLC_BATTLE_MIX3_CLUB_PRIV"),
	DLC_BATTLE_MIX4_CLUB_PRIV("DLC_BATTLE_MIX4_CLUB_PRIV"),

	HIDDEN_RADIO_01_CLASS_ROCK("HIDDEN_RADIO_01_CLASS_ROCK"),
	HIDDEN_RADIO_02_POP("HIDDEN_RADIO_02_POP"),
	HIDDEN_RADIO_03_HIPHOP_NEW("HIDDEN_RADIO_03_HIPHOP_NEW"),
	HIDDEN_RADIO_04_PUNK("HIDDEN_RADIO_04_PUNK"),
	HIDDEN_RADIO_06_COUNTRY("HIDDEN_RADIO_06_COUNTRY"),
	HIDDEN_RADIO_07_DANCE_01("HIDDEN_RADIO_07_DANCE_01"),
	HIDDEN_RADIO_09_HIPHOP_OLD("HIDDEN_RADIO_09_HIPHOP_OLD"),
	HIDDEN_RADIO_12_REGGAE("HIDDEN_RADIO_12_REGGAE"),
	HIDDEN_RADIO_15_MOTOWN("HIDDEN_RADIO_15_MOTOWN"),
	HIDDEN_RADIO_16_SILVERLAKE("HIDDEN_RADIO_16_SILVERLAKE"),
	HIDDEN_RADIO_ADVERTS("HIDDEN_RADIO_ADVERTS"),
	HIDDEN_RADIO_AMBIENT_TV("HIDDEN_RADIO_AMBIENT_TV"),
	HIDDEN_RADIO_AMBIENT_TV_BRIGHT("HIDDEN_RADIO_AMBIENT_TV_BRIGHT"),
	HIDDEN_RADIO_BIKER_CLASSIC_ROCK("HIDDEN_RADIO_BIKER_CLASSIC_ROCK"),
	HIDDEN_RADIO_BIKER_HIP_HOP("HIDDEN_RADIO_BIKER_HIP_HOP"),
	HIDDEN_RADIO_BIKER_MODERN_ROCK("HIDDEN_RADIO_BIKER_MODERN_ROCK"),
	HIDDEN_RADIO_BIKER_PUNK("HIDDEN_RADIO_BIKER_PUNK"),
	HIDDEN_RADIO_STRIP_CLUB("HIDDEN_RADIO_STRIP_CLUB"),
	;
}